package tr.edu.deu.efm.command.api;

/**
 * An immutable Data Transfer Object (DTO) representing the final outcome of a
 * command execution.
 * <p>
 * This class ensures a strict decoupling between the execution logic
 * (Core/Commands) and the presentation layer (UI). Instead of commands printing
 * directly to the console or forcefully terminating the JVM, they return this
 * strictly structured result. The receiving layer then decides how to display
 * the message or whether to halt the application loop.
 * </p>
 * <p>
 * <b>Immutability:</b> All fields are {@code final}, guaranteeing that once a
 * command evaluates its result, the outcome cannot be maliciously or
 * accidentally altered in transit.
 * </p>
 */
public class CommandResult {

	private final boolean success;
	private final String message;
	private final boolean terminateProgram;

	/**
	 * Constructs a standard command result where the application is expected to
	 * continue running.
	 *
	 * @param success {@code true} if the command executed without errors;
	 *                {@code false} otherwise.
	 * @param message The standard output or error message to be displayed to the
	 *                user.
	 */
	public CommandResult(boolean success, String message) {
		this.success = success;
		this.message = message;
		this.terminateProgram = false;
	}

	/**
	 * Constructs a command result with an explicit instruction regarding the
	 * application's lifecycle.
	 * <p>
	 * Typically utilized by termination commands (e.g., {@code ExitCommand}) to
	 * gracefully signal the main application loop to shut down.
	 * </p>
	 *
	 * @param success          {@code true} if the command executed without errors.
	 * @param message          The parting message or final output to be displayed.
	 * @param terminateProgram {@code true} to signal the main loop to break and
	 *                         exit the system.
	 */
	public CommandResult(boolean success, String message, boolean terminateProgram) {
		this.success = success;
		this.message = message;
		this.terminateProgram = terminateProgram;
	}

	/**
	 * @return {@code true} if the operation was successful, influencing whether the
	 *         UI prints the message to {@code System.out} or {@code System.err}.
	 */
	public boolean isSuccess() {
		return success;
	}

	/**
	 * @return The formatted string output generated by the command. May be empty,
	 *         but never null.
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * @return {@code true} if this result indicates that the user session should be
	 *         closed.
	 */
	public boolean isTerminateProgram() {
		return terminateProgram;
	}
}